### PR TITLE
Added ReleaseDrafter configuration files

### LINKED ISSUE #70: [CI] Setup ReleaseDrafter
**Current Situation**
The [ReleaseDrafter](https://github.com/marketplace/actions/release-drafter) utility (GitHub Action) is not configured in this repository.

**Desired Situation**
- Releasedrafter should be configured to execute whenever a PR is merged to master in this repo.

**Implementation**
- Copy the [releasedrafter config](https://github.com/layer5io/meshery/blob/master/.github/release-drafter.yml) and the [releasedrafter workflow](https://github.com/layer5io/meshery/blob/master/.github/workflows/release-drafter.yml) file from the `meshery` repo and place in the `.github` folder here.

### PR DESCRIPTION
**Pull request by mgfeller**
Signed-off-by: Michael Gfeller <mgfeller@mgfeller.net>

This PR fixes #70

### CODE REVIEW

**Comment by Neilblaze** [comment]
LGTM :+1: 
Good job @mgfeller :smiley:

**Comment by leecalcote** [comment]
Oh, no! There's no celebration message for @mgfeller's first PR being merged here! We'll have to do something about this!

**Comment by PluckyPrecious** [comment]
@mgfeller forgive our meshy repo.
🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🎉🎉🎉🎉🎉🥳🥳🥳🥳🥳THANKS FOR YOUR CONTRIBUTION TO THE LAYER5 COMMUNITY 🎉🎉🎉🎉🎉🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳 🎉 🎉🎉🎉🎉

**Comment by mgfeller** [comment]
@PluckyPrecious thanks! It's a pleasure and very satisfying :fireworks: :partying_face: !!

**Pull request merged**
