### PR TITLE
add statically generated pattern components for Consul

### PR DESCRIPTION
**Pull request by DelusionalOptimist**
Signed-off-by: Rudraksh Pareek <rudrakshpareek3601@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**
Generated using much frowned upon and delusionally optimistic methods https://gist.github.com/DelusionalOptimist/7e870dc17bf80277b48cd840aaa0ca9d

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Do we have a workflow in this repo to build components? @Revolyssup

**Comment by DelusionalOptimist** [comment]
Thank you for pointing this out @sayantan1413 @leecalcote. I'll update either of the PRs with a workflow :+1:

**Comment by DelusionalOptimist** [comment]
@Revolyssup I tried using the static components with this updated Docker image to check if they were getting registered. They were not.
Logs:
```
kubectl logs -n meshery meshery-consul-94fd7df9f-k4jz5 -f                         
{"app":"consul-adapter","level":"info","msg":"KUBECONFIG: /home/appuser/.meshery/kubeconfig.yaml","time":"2021-10-09T12:47:04Z"}
{"app":"consul-adapter","level":"info","msg":"Registering static workloads...","time":"2021-10-09T12:47:04Z"}
{"app":"consul-adapter","level":"info","msg":"Adaptor Listening at port: 10002","time":"2021-10-09T12:47:04Z"}
{"app":"consul-adapter","level":"info","msg":"Could not get manifest names json: cannot unmarshal number into Go struct field treeslice.tree of type string","time":"2021-10-09T12:47:05Z"}
```
Please look into this.

**Comment by Revolyssup** [comment]
> @Revolyssup I tried using the static components with this updated Docker image to check if they were getting registered. They were not. Logs:
> 
> ```
> kubectl logs -n meshery meshery-consul-94fd7df9f-k4jz5 -f                         
> {"app":"consul-adapter","level":"info","msg":"KUBECONFIG: /home/appuser/.meshery/kubeconfig.yaml","time":"2021-10-09T12:47:04Z"}
> {"app":"consul-adapter","level":"info","msg":"Registering static workloads...","time":"2021-10-09T12:47:04Z"}
> {"app":"consul-adapter","level":"info","msg":"Adaptor Listening at port: 10002","time":"2021-10-09T12:47:04Z"}
> {"app":"consul-adapter","level":"info","msg":"Could not get manifest names json: cannot unmarshal number into Go struct field treeslice.tree of type string","time":"2021-10-09T12:47:05Z"}
> ```
> 
> Please look into this.

The error is from dynamic component registration and yes thats not working rn because that requires one of the functions which was to be moved to meshkit(the gitwalker function) Although static components are being registered with no problem

**Pull request merged**
