### PR TITLE
README update

### LINKED ISSUE #153: [README] Update README Community Section
**Description**
The Community section in the README says "Access the Community Drive". There is a new procedure of having this automated based on the individual filling in a [community member form](https://layer5.io/newcomer)

**Expected Behavior**
Update "Access Community Drive" to "To Access Community Drive, fill Community Member Form"

**Screenshots**
img
--

**Resources**
Refer to the [Contributing guide](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#contributing)

**Environment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

### PR DESCRIPTION
**Pull request by cristiangutie**
Signed-off-by: Cristián Gutiérrez <cristian.gutie@gmail.com>

**Description**

This PR fixes #153
**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [X] Yes, I signed my commits.

### CODE REVIEW

**Review by Anita-ihuman — COMMENTED** [review]
Thank you for taking up this issue.
 You can remove the link in the Community drive and we are good to go.

**Comment by cristiangutie** [comment]
Done @Anita-ihuman. Tell me if I can help you with anything else. Have a nice day!

**Review by Anita-ihuman — APPROVED** [review]
Great work @cristiangutie, you can explore the other repositories for issues. Have a great day.

**Review by leecalcote — APPROVED** [review]
Thank you, @cristiangutie 👍

**Pull request merged**
